config/routes.rb
Amber::Application.routes.draw do
  root 'home#index'
  get 'photos' => 'home#photos'
  get 'settings' => 'users#edit', as: :settings

  controller :sessions do
    #get '/signin' => :new, as: :signin
    get '/signout' => :destroy, as: :signout
    get '/auth/:provider/callback' => :create
    get '/auth/failure' => :failure
  end

  resources :sessions, only: [:new, :create, :destroy, :failure]
  resources :users, only: [:show, :edit, :update] do
    get :setup, :on => :member
    get :info, :on => :member, as: :info
    resources :photos, only: [:index]
    resources :bookmarks, only: [:index]
  end
  resources :photos, except: :index do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :categories, only: :show
  resources :pages, only: :show
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :notifications, only: [:index, :read, :viewed, :clear] do
    member do
      get :read
    end

    collection do
      get :viewed
      get :clear
    end
  end

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :destroy]
    resources :photos, only: [:index, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :pages, except: :show
    resources :tips, except: :show
  end

  # resources :identities, only: :new

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/views/admin/pages/edit.html.erb
<% provide(:title, "编辑页面") %>
<%= form_for [:admin, @page] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :created_at %>
      <%= f.datetime_select :created_at %>
    </div>
    <div class="large-6 columns">
      <%= f.label :updated_at %>
      <%= f.datetime_select :updated_at %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "编辑页面！", data: { disable_with: "编辑页面中..." } %>
  </div>
<% end %>

app/views/admin/pages/index.html.erb
<% provide(:title, "管理页面") %>
<h2>所有页面<small><%= link_to "添加新页面", new_admin_page_path %></small></h2>
<table>
  <thead>
    <tr>
      <th width="100">slug</th>
      <th width="200">标题</th>
      <th width="200">创建时间</th>
      <th width="50">编辑</th>
      <th width="50">删除</th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.slug %></td>
      <td><%= link_to page.title, page %></td>
      <td><%= format_time page.created_at %></td>
      <td><%= link_to "编辑", edit_admin_page_path(page) %></td>
      <td><%= link_to "删除", admin_page_path(page), method: :delete, data: { confirm: '你确定删除该页面？再想想？' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination-centered">
  <ul class="pagination arrow">
    <%= paginate @pages %>
  </ul>
</div>

app/views/admin/pages/new.html.erb
<% provide(:title, "新页面") %>
<%= form_for [:admin, @page] do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :created_at %>
      <%= f.datetime_select :created_at %>
    </div>
    <div class="large-6 columns">
      <%= f.label :updated_at %>
      <%= f.datetime_select :updated_at %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "创建页面！", data: { disable_with: "创建页面中..." } %>
  </div>
<% end %>