config/routes.rb
Amber::Application.routes.draw do
  root 'home#index'
  get 'photos' => 'home#photos'
  get 'settings' => 'users#edit', as: :settings

  controller :sessions do
    #get '/signin' => :new, as: :signin
    get '/signout' => :destroy, as: :signout
    get '/auth/:provider/callback' => :create
    get '/auth/failure' => :failure
  end

  resources :sessions, only: [:new, :create, :destroy, :failure]
  resources :users, only: [:show, :edit, :update] do
    get :setup, :on => :member
    get :info, :on => :member, as: :info
    resources :photos, only: [:index]
    resources :bookmarks, only: [:index]
  end
  resources :photos, except: :index do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :categories, only: :show
  resources :pages, only: :show
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :notifications, only: [:index, :read, :viewed, :clear] do
    member do
      get :read
    end

    collection do
      get :viewed
      get :clear
    end
  end

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :destroy]
    resources :photos, only: [:index, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :pages, except: :show
    resources :tips, except: :show
  end

  # resources :identities, only: :new

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  ACTION_MENTION = 'mention'
  ACTION_REPLY = 'reply'

  belongs_to :user
  belongs_to :action_user, :class_name => 'User'
  belongs_to :notifiable, :polymorphic => true

  # Notify user
  def self.notify(user, notifiable, action_user, action, content)
    notification = Notification.new(:action => action, :content => content)
    notification.notifiable = notifiable
    notification.user = user
    notification.action_user = action_user
    notification.save
  end

  def action_info_prefix
    case self.action
    when ACTION_MENTION
      '在回复'
    when ACTION_REPLY
      '在'
    end
  end

  def action_info_suffix
    case self.action
    when ACTION_MENTION
      '时提到'
    when ACTION_REPLY
      '里回复'
    end
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :signed_in_user, only: [:index, :read, :viewed, :clear]

  def index
    @notifications = current_user.notifications.where(:unread => true).includes(:action_user).order('created_at DESC')
    @viewed = current_user.notifications.where(:unread => false).includes(:action_user).order('created_at DESC').limit(25)
  end

  def read
    @notification = current_user.notifications.find(params[:id])
    if @notification.present?
      @notification.update(:unread => false)
      redirect_to @notification.notifiable.notifiable_path
    else
      redirect_to root_path, :alert => "无法处理之前的请求！"
    end
  end

  def viewed
    if current_user.notifications.where(:unread => true).update_all(:unread => false)
      redirect_to notifications_path, notice: "未读消息已全部标记为已读。"
    else
      flash.now.alert = "全部标记为已读失败！"
      render :index
    end
  end

  def clear
    if current_user.notifications.destroy_all
      redirect_to root_path, notice: "已清空消息。"
    else
      flash.now.alert = "清空失败！"
      render :index
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unread_notification_count
    @unread_count = current_user.notifications.where(:unread => true).count
  end

  def format_notification(text)
    truncate(text, length: 25)
  end
end

app/views/notifications/_notification.html.erb
<div class="panel">
  <%= link_to resize_avatar(notification.action_user, "square32"), notification.action_user %>
  <b><%= notification.action_user.name %></b>
  <%= notification.action_info_prefix %>
  <%= link_to format_notification(notification.content), read_notification_path(notification) %>
  <%= notification.action_info_suffix %>了你
  <small><%= format_time notification.created_at %></small>
</div>

app/views/notifications/index.html.erb
<% provide(:title, "消息提醒") %>
<% content_for :subhead do %>
  <h2>消息提醒</h2>
<% end %>
<dl class="tabs vertical" data-tab>
  <dd class="active"><a href="#panel1a">未读消息</a></dd>
  <dd><a href="#panel2a">已读消息</a></dd>
</dl>
<div class="tabs-content vertical">
  <div class="content active" id="panel1a">
    <%= link_to "全部记为已读", viewed_notifications_path, :class => "tiny button" %>
    <%= render @notifications %>
  </div>
  <div class="content" id="panel2a">
    <%= link_to "清空消息", clear_notifications_path, :class => "tiny button" %>
    <% @viewed.each do |notification| %>
      <% if notification.action_user %>
        <%= render "notification", notification: notification %>
      <% end %>
    <% end %>
  </div>
</div>