config/routes.rb
Amber::Application.routes.draw do
  root 'home#index'
  get 'photos' => 'home#photos'
  get 'settings' => 'users#edit', as: :settings

  controller :sessions do
    #get '/signin' => :new, as: :signin
    get '/signout' => :destroy, as: :signout
    get '/auth/:provider/callback' => :create
    get '/auth/failure' => :failure
  end

  resources :sessions, only: [:new, :create, :destroy, :failure]
  resources :users, only: [:show, :edit, :update] do
    get :setup, :on => :member
    get :info, :on => :member, as: :info
    resources :photos, only: [:index]
    resources :bookmarks, only: [:index]
  end
  resources :photos, except: :index do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :categories, only: :show
  resources :pages, only: :show
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :notifications, only: [:index, :read, :viewed, :clear] do
    member do
      get :read
    end

    collection do
      get :viewed
      get :clear
    end
  end

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :destroy]
    resources :photos, only: [:index, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :pages, except: :show
    resources :tips, except: :show
  end

  # resources :identities, only: :new

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/views/shared/_bookmark_button.html.erb
<% if current_user %>
  <% if current_user.bookmarked?(thing) %>
    <%= link_to "取消收藏", current_user.bookmark_of(thing), :method => :delete, :class => "button", :id => "bookmark", data: { disable_with: "取消中..." } %>
  <% else %>
    <%= link_to "加入收藏", photo_bookmarks_path(thing), :method => :post, :class => "button", :id => "bookmark", data: { disable_with: "加入中..." } %>
  <% end %>
<% end %>

app/views/shared/_errors.html.erb
<% if model.errors.any? %>
  <b>更新出错！！！</b>
  <ul class="errors">
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_paginate.html.erb
<div class="pagination-centered">
  <ul class="pagination arrow">
    <%= paginate photos %>
  </ul>
</div>

app/views/shared/_photo_grid.html.erb
<ul class="small-block-grid-4">
  <% photos.each do |photo| %>
  <li>
    <div class="img-wrapper">
      <%= link_to resize(photo, "square240"), photo %>
      <div class="img-caption">
        <span class="img-caption-photo-title"><%= photo.title %></span>
        <span class="img-caption-photo-user"><%= photo.user.name %></span>
      </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/shared/_tip.html.erb
<div class="tip">
  <h5 class="subheader">小贴士</h5>
  <%= @tip.body %>
</div>