config/routes.rb
Amber::Application.routes.draw do
  root 'home#index'
  get 'photos' => 'home#photos'
  get 'settings' => 'users#edit', as: :settings

  controller :sessions do
    #get '/signin' => :new, as: :signin
    get '/signout' => :destroy, as: :signout
    get '/auth/:provider/callback' => :create
    get '/auth/failure' => :failure
  end

  resources :sessions, only: [:new, :create, :destroy, :failure]
  resources :users, only: [:show, :edit, :update] do
    get :setup, :on => :member
    get :info, :on => :member, as: :info
    resources :photos, only: [:index]
    resources :bookmarks, only: [:index]
  end
  resources :photos, except: :index do
    resources :comments, only: [:create, :destroy]
    resources :bookmarks, only: [:create, :destroy]
  end
  resources :categories, only: :show
  resources :pages, only: :show
  resources :comments, only: [:create, :destroy]
  resources :bookmarks, only: [:create, :destroy]
  resources :notifications, only: [:index, :read, :viewed, :clear] do
    member do
      get :read
    end

    collection do
      get :viewed
      get :clear
    end
  end

  namespace :admin do
    root 'home#index'
    resources :users, only: [:index, :destroy]
    resources :photos, only: [:index, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :pages, except: :show
    resources :tips, except: :show
  end

  # resources :identities, only: :new

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable
end

app/models/tip.rb
class Tip < ActiveRecord::Base
end

app/controllers/admin/tips_controller.rb
class Admin::TipsController < ApplicationController
  layout 'admin'
  before_action :admin_user?, only: [:index, :new, :create, :edit, :destroy]

  def index
    @tips = Tip.order("created_at DESC").page params[:page]
  end

  def new
    @tip = Tip.new
  end

  def create
    @tip = Tip.new(tip_params)
    if @tip.save
      redirect_to admin_tips_path, notice: "创建tip成功！"
    else
      flash.now.alert = "创建tip失败..."
      render :new
    end
  end

  def edit
    @tip = Tip.find(params[:id])
  end

  def update
    @tip = Tip.find(params[:id])
    if @tip.update(tip_params)
      redirect_to tip_path(@tip), notice: "编辑tip成功！"
    else
      flash.now.alert = "编辑tip失败..."
      render :edit
    end
  end

  def destroy
    @tip = Tip.find(params[:id])
    if @tip.destroy
      redirect_to admin_tips_path, notice: "删除tip成功！"
    else
      flash.now.alert = "删除tip失败..."
      render :edit
    end
  end

  private
    def tip_params
      params.require(:tip).permit(:body, :created_at, :updated_at)
    end
end

app/helpers/admin/tips_helper.rb
module Admin::TipsHelper
end

app/views/admin/tips/edit.html.erb
<% provide(:title, "编辑贴士") %>
<%= form_for [:admin, @tip] do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :created_at %>
      <%= f.datetime_select :created_at %>
    </div>
    <div class="large-6 columns">
      <%= f.label :updated_at %>
      <%= f.datetime_select :updated_at %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "编辑贴士！", data: { disable_with: "编辑贴士中..." } %>
  </div>
<% end %>

app/views/admin/tips/index.html.erb
<% provide(:title, "管理贴士") %>
<h2>所有贴士<small><%= link_to "添加新贴士", new_admin_tip_path %></small></h2>
<table>
  <thead>
    <tr>
      <th width="200">创建时间</th>
      <th width="800">内容</th>
      <th width="50">编辑</th>
      <th width="50">删除</th>
    </tr>
  </thead>
  <tbody>
    <% @tips.each do |tip| %>
    <tr>
      <td><%= format_time tip.created_at %></td>
      <td><%= tip.body %></td>
      <td><%= link_to "编辑", edit_admin_tip_path(tip) %></td>
      <td><%= link_to "删除", admin_tip_path(tip), method: :delete, data: { confirm: '你确定删除该贴士？再想想？' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="pagination-centered">
  <ul class="pagination arrow">
    <%= paginate @tips %>
  </ul>
</div>

app/views/admin/tips/new.html.erb
<% provide(:title, "新贴士") %>
<%= form_for [:admin, @tip] do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <%= f.label :created_at %>
      <%= f.datetime_select :created_at %>
    </div>
    <div class="large-6 columns">
      <%= f.label :updated_at %>
      <%= f.datetime_select :updated_at %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "创建贴士！", data: { disable_with: "创建贴士中..." } %>
  </div>
<% end %>